### PR TITLE
convert to .net core with multi-targeting for .net 4.6 and 4.5

### PR DESCRIPTION
**Pull request by jjafuller**
I believe this should be good to go. I did not see any CI tooling here, so I assume you are building the nuget package manually. The process will be a little different for this now. All you have to do is go into the AutofacContrib.NSubstitute project and type `dotnet pack`. First, you'll need to install the latest .netcore toolkit if you haven't already.

### CODE REVIEW

**Comment by jjafuller** [comment]
I see that you are using TeamCity for the build. You'll probably have to update the test phase to run `dotnet test`.

**Comment by mtrtm** [comment]
I'm a bit worried this project is abandoned - has anyone heard anything?  It would be great to get this pull request done as well as mine so we can have some current support

**Comment by robdmoore** [comment]
Hi,

@MattDavies and I don't really use this library anymore - we actually prefer to avoid mocking libraries in general.

Regardless, the CI of all of our projects recently got upgraded to app veyor so if you push a change to this PR it should get rebuilt and if it passes I'm happy to release.

I just merged some open PRs that add conflicts to this PR FYI.

**Comment by mozerov** [comment]
Hi, 

Is there any info about this PR?

**Comment by jjafuller** [comment]
I am not sure how I missed this. I will get those conflicts resolved as soon as I can.

**Comment by jjafuller** [comment]
I am going to close this PR as it is now superseded by https://github.com/MRCollective/AutofacContrib.NSubstitute/pull/33

**Pull request closed without merging**
