### PR TITLE
Update to Autofac v3.5.2

### PR DESCRIPTION
**Pull request by BrainCrumbz**

### CODE REVIEW

**Comment by robdmoore** [comment]
Are you able to rebase to remove that merge commit and also include a change to the dependency in the nuspec file?

Thanks :)

**Comment by BrainCrumbz** [comment]
Yes I rebased, but then I think I sync'ed Github Client locally. Trying again

**Comment by BrainCrumbz** [comment]
Please have a look at it again now.

**Comment by robdmoore** [comment]
I pushed out 3.3.5 to NuGet with this change

**Pull request merged**
