### PR TITLE
chore(deps): upgrade Autofac to 4.1.1 and switch to .NET 4.5.2

### PR DESCRIPTION
**Pull request by BrainCrumbz**

### CODE REVIEW

**Comment by BrainCrumbz** [comment]
Hi.
Any chance to have a look at this PR and #23 ? Regards

**Comment by robdmoore** [comment]
@BrainCrumbz sorry for the delay.

Mind fixing the conflicts?

Then I'll ,merge and release :)

**Comment by BrainCrumbz** [comment]
Conflicts gone. Happy merge & release!

**Comment by BrainCrumbz** [comment]
Please drop a line when new version is published. Thanks!

**Comment by robdmoore** [comment]
Is already :)

--

**Pull request merged**
