### PR TITLE
Update to NSubstitute v1.9.2

### PR DESCRIPTION
**Pull request by BrainCrumbz**

### CODE REVIEW

**Comment by robdmoore** [comment]
Can you please update the nuspec file too?

**Comment by BrainCrumbz** [comment]
:+1:

**Comment by BrainCrumbz** [comment]
Please let us know when the updated package is out, so that we can update our projects to NSubstitute and this as well. Thanks!

**Comment by BrainCrumbz** [comment]
Hello. Any update on this? Thanks

**Comment by BrainCrumbz** [comment]
Up

**Comment by robdmoore** [comment]
My apologies.

I'll do this now.

**Comment by robdmoore** [comment]
Published :)

Sorry for the delay.

**Comment by BrainCrumbz** [comment]
:) :+1:

**Pull request merged**
